name: Deploy to PyPI

#on:
#  release:
#    types: [published]
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install setuptools and wheel
        run: >-
          python -m
          pip install
          --user
          --upgrade
          setuptools
          wheel

      - name: Build a binary wheel and gz file
        run: >-
          python setup.py sdist bdist_wheel

      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
         password: ${{ secrets.PYPI_PASSWORD }}
