name: Deploy to PyPI

#on:
#  release:
#    types: [published]
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Stop previous build
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GH_TOKEN_PARETO_BOT }}

      - name: Checkout to branch
        uses: actions/checkout@v1

      - name: Get Changed Files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '

      - name: Install setuptools and wheel
        run: >-
          python -m
          pip install
          --user
          --upgrade
          setuptools
          wheel

      - name: Build a binary wheel and gz file
        run: >-
          python setup.py sdist bdist_wheel

      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
         password: ${{ secrets.PYPI_PASSWORD }}
